### ISSUE TITLE
Special Use Case - Unity - Built-in Methods (Messaging System) are Coloured Like Keywords

### ISSUE THREAD

**Issue by kwalkerxxi** [Swiftly1/CsharpToColouredHTML#17]
## **_Note: not really an issue. More a special use case that is not currently supported._**

**Overview:**
I am mostly using your library to convert C Sharp code that is used within Unity. 

Within Visual Studio the integration allows built-in Unity method names (which are called by their messaging system - see here under **Messages** heading: [Unity API on Monobehaviour](https://docs.unity3d.com/ScriptReference/MonoBehaviour.html)) to be coloured like they are keywords.

This may not be something you wish to add but I thought I'd show you my fix - it works well for me. You may even have a suggestion regarding a better way to do it...

# My initial issue:

![1 My Issue](https://user-images.githubusercontent.com/4986692/213722987-f01edcb0-9422-4deb-bd38-8081bef75d72.png)
![2 My Ideal Situation](https://user-images.githubusercontent.com/4986692/213723005-d67e41dd-1047-4d6b-9d88-f8cef30ddb43.png)

# My implemented fix:

![3 My Fix](https://user-images.githubusercontent.com/4986692/213723012-7b255685-1a2b-4e2e-a34b-a927a9a4fd94.png)

**_Code added in Hints.cs:_**

```
public List<string> ReallyPopularMethod { get; } = new List<string>
    {
        "Awake",
        "FixedUpdate",
        "LateUpdate",
        "OnAnimatorIK",
        "OnAnimatorMove",
        "OnApplicationFocus",
        "OnApplicationPause",
        "OnApplicationQuit",
        "OnAudioFilterRead",
        "OnBecameInvisible",
        "OnBecameVisible",
        "OnBeforeTransformParentChanged",
        "OnCanvasGroupChanged",
        "OnCollisionEnter",
        "OnCollisionEnter2D",
        "OnCollisionExit",
        "OnCollisionExit2D",
        "OnCollisionStay",
        "OnCollisionStay2D",
        "OnConnectedToServer",
        "OnControllerColliderHit",
        "OnDestroy",
        "OnDisable",
        "OnDisconnectedFromMasterServer",
        "OnDisconnectedFromServer",
        "OnDrawGizmos",
        "OnDrawGizmosSelected",
        "OnEnable",
        "OnFailedToConnect",
        "OnFailedToConnectToMasterServer",
        "OnGUI",
        "OnJointBreak",
        "OnJointBreak2D",
        "OnLevelWasLoaded",
        "OnMasterServerEvent",
        "OnMouseDown",
        "OnMouseDrag",
        "OnMouseEnter",
        "OnMouseExit",
        "OnMouseOver",
        "OnMouseUp",
        "OnMouseUpAsButton",
        "OnNetworkInstantiate",
        "OnParticleCollision",
        "OnParticleSystemStopped",
        "OnParticleTrigger",
        "OnParticleUpdateJobScheduled",
        "OnPlayerConnected",
        "OnPlayerDisconnected",
        "OnPostRender",
        "OnPreCull",
        "OnPreRender",
        "OnRectTransformDimensionsChange",
        "OnRectTransformRemoved",
        "OnRenderImage",
        "OnRenderObject",
        "OnSerializeNetworkView",
        "OnServerInitialized",
        "OnTransformChildrenChanged",
        "OnTransformParentChanged",
        "OnTriggerEnter",
        "OnTriggerEnter2D",
        "OnTriggerExit",
        "OnTriggerExit2D",
        "OnTriggerStay",
        "OnTriggerStay2D",
        "OnValidate",
        "OnWillRenderObject",
        "Reset",
        "Start",
        "Update"
    };
```

**_Code added in HeuristicsGenerator.cs, at end of PostProcess method:_**

```
 //Added This for Unity Built-In Method Color Support
        for (int i = 0; i < alreadyProcessed.Count; i++)
        {
            var current = alreadyProcessed[i];
            if (_Hints.ReallyPopularMethod.Contains(current.Text))
                current.Colour = NodeColors.Keyword;
        }
```

**Comment by Swiftly1** [comment]
At the first glance I think I'd rather allow caller to provide his own post processing method via e.g Funcs/Actions

So this way "Core" stays as small as possible, yet callers can still extend it or affect the result by providing their own post processing.

Those custom post processing extensions could be available from other or community Nugets and work kinda as plugins.

So somebody adds to his project nuget to my `Core`, then adds nuget extension for e.g Unity and it integrates together 

_____________

I will think about the design and its implications soon.

**Comment by Swiftly1** [comment]
I've created some sample implementation for this post processing

Please let me know whether it allows you achieve your goal

Here's PR with sample code, you can switch on that branch and try it yourself https://github.com/Swiftly1/CsharpToColouredHTML/pull/19

**Comment by kwalkerxxi** [comment]
Hmmm.... I really like your solution in  ***Allowing External Post-processing*** [#19](https://github.com/Swiftly1/CsharpToColouredHTML/pull/19)  I'll give it a go. Note my comment in issue #18 about using an INI file to input the list into the program.

**Comment by kwalkerxxi** [comment]
I noticed you updated to .netcore7 - I'm a bit busy but will try to upgrade and test it when I can. The start of the year is always crazy busy for me. If I don't get back to you quickly please take no offense.

**Comment by Swiftly1** [comment]
Implemented in https://github.com/Swiftly1/CsharpToColouredHTML/pull/19

Thanks for the feedback, I think both of those capabilities are really cool :) 

New version - 1.0.38 has been released.
