### ISSUE TITLE
Highlighting Important Lines

### ISSUE THREAD

**Issue by kwalkerxxi** [Swiftly1/CsharpToColouredHTML#18]
Not required but I would love to have it...

Have you thought about adding the feature of highlighting lines (and/or just showing partial sections of code).

They do this in DocFX using some Markdown syntax.

See here for example syntax and usage: 

- [https://dotnet.github.io/docfx/docs/markdown.html#highlight-selected-lines](https://dotnet.github.io/docfx/docs/markdown.html#highlight-selected-lines)
- [https://dotnet.github.io/docfx/docs/markdown.html#code-snippet](https://dotnet.github.io/docfx/docs/markdown.html#code-snippet)

You could allow the user to supply line numbers and just put <mark></mark> tags around the line. I might have a go at implementing it myself.

**Comment by Swiftly1** [comment]
I think it is a great idea, but I'm not sure how it'd look visually

You mean something like Github's? e.g `https://github.com/Swiftly1/CsharpToColouredHTML/blob/master/src/Core/CsharpColourer.cs#L46-L49`

![obraz](https://user-images.githubusercontent.com/77643169/213873939-2aad6b82-fd20-4a55-9c90-21ff6e626f16.png)

When I tried underline, then it'd be kinda ugly when applied on the whole row

![obraz](https://user-images.githubusercontent.com/77643169/213874247-a9247de1-8456-479e-be68-e677b880991e.png)

meanwhile with optimizations enabled it'd be difficult to put just under the words (even with optimizations disabled it's tricky)

![obraz](https://user-images.githubusercontent.com/77643169/213874190-91d09f64-9667-418e-9686-c76dab64d578.png)

So, I'd rather add the GitHub's highlight because it'd be trivial and looks better, imo.

Example:

![obraz](https://user-images.githubusercontent.com/77643169/213874383-852efeb5-6b97-4421-8a10-1821a99557ad.png)

When it comes to API, then I think caller would be able to provide something like that:

```csharp
var highlightRanges = new List<Range>
{
	new Range(1), // single line
	new Range(start: 5, end: 15), // both start and end are inclusive, so 5th and 25th lines are marked too 
	new Range(25), // single line
	new Range(start: 26, end: 98),
}
```

that's very first idea


I could expose some highlight CSS property that would allow you to configure the colour flexibly, but when the caller provides his/her own CSS, then it'd be ignored. 

I'll think about it and implement it once I come up with something good

**Comment by kwalkerxxi** [comment]
Github seems to do it like DocFX (and I like it too - so I also landed on the whole line approach - as you do in your proposal).

Here's what I did to get it working (very rough - making a list and cleaning up my implementation would be great):

I allowed the user who drags-and-drops multiple CS files onto the CLI executable to just have output without line numbers. However, if they drag-and-drop a single file, they will be prompted for the line to highlight (looped so they can specify each line). As I said, very clunky. **Being able to feed it into a Range list is a much better idea!**. I think this could be done like you did in issue #17 similar to the Action<List< NodeAfterProcessing >> (maybe a TR After Processing method?)

You might note that I start my line count at 1 instead of 0 and that I am now using an INI file to feed in the list of extra methods to format from an INI file that looks something like this (I am thinking I could put line number ranges in the INI as well if you make the API **highlightRanges** function as suggested - although I like the idea of it being more dynamic as it changes per file...):

```
[TeacherCodeToChange] - Highlights with CSS background color and rounded corners
cachedRigidbody
TagToCheckAgainst
[ReallyPopularClasses] - forces class formatting (in case it gets missed)
UnityEvent
[ReallyPopularMethods] -  formats like keyword
Start
```

See screenshot and my ***very rushed*** implementation below

![CLI Eg 2](https://user-images.githubusercontent.com/4986692/214847750-0fb90dc1-5f03-4e8c-9bb0-eadb3faec7be.png)

In the **HTMLEmitter class**

```
    public string Emit(List<NodeWithDetails> nodes, List<int> lineNumbersToHighlight)
    {
        Reset();

        // Optimizer - Merges Nodes with the same colour
        if (Optimize)
        {
            OptimizeNodes(nodes);
        }

        var html = AddLineNumber ? GenerateHtmlWithLineNumbers(nodes, lineNumbersToHighlight) : GenerateHtml(nodes);
        return UseIframe ? AddIframe(html) : html;
    }



     private string GenerateHtmlWithLineNumbers(List<NodeWithDetails> nodes, List<int>? highlightedLineNumbers = null)
    {
        var sb = new StringBuilder();

        sb.AppendLine(_cssHelper.GetCSS(AddLineNumber, Optimize, nodes, _MostCommonColourValue));
        sb.AppendLine(@"<pre class=""background"">" );

        var isOpened = false;

        sb.AppendLine("<table>" );
        sb.AppendLine("<tbody>" );

        for (int i = 0; i < nodes.Count; i++)
        {
            var current = nodes[i];
            if (i == 0 || current.HasNewLine)
            {
                if (isOpened)
                {                   
                    sb.Append("</td></tr>" );
                }

                AddRowsForNewLinesIfNeededToStringBuilder(current.Trivia, sb);

                sb.Append("<tr>");
                AddNewLineNumberToStringBuilder(sb);

                //Hoey Added 
                bool lineMatch = false;
                if (highlightedLineNumbers != null)
                {
                    

                    foreach (var line in highlightedLineNumbers)
                    {
                        if (_LineCounter == line+1) //Original starts numbering at zero - I prefer to start at 1 like VS
                        {
                         lineMatch= true;                        
                        }                       
                    }
                }

                if (lineMatch) 
                {
                    sb.Append("<td class=\"code_column\" style=\"background-color: #1F62A9; color: #dfdfdf;\">");
                    // highlightedLineNumbers.Remove(line);

                }
                else
                {
                    sb.Append("<td class=\"code_column\">");
                }

                isOpened = true;
            }

            var postProcessed = PostProcessing(current);

            var span = current.UsesMostCommonColour ?
                $"{postProcessed.Before}{postProcessed.Content}{postProcessed.After}" :
                @$"{postProcessed.Before}<span class=""{current.Colour}"">{postProcessed.Content}</span>{postProcessed.After}";
            //Console.WriteLine($"{_LineCounter} { postProcessed.Content}");
            sb.Append(RemoveNewLines(span));
        }

        if (isOpened)
        {
            sb.Append("</td></tr>" );
        }

        sb.AppendLine("</tbody>" );
        sb.Append("</table>"  );
        sb.AppendLine("</pre>");

        return sb.ToString();
    }

```

In the **CsharpColourer class**

```
    public string ProcessSourceCode(string code, IEmitter emitter, List<int> lineNumbersToHighlight)
    {
        code = code.ReplaceLineEndings();
        var nodes = GenerateInternalRepresentation(code);
        var heuristics = new HeuristicsGenerator(Hints).Build(nodes);
        return emitter.Emit(heuristics, lineNumbersToHighlight);
    }

```

Then in the CLI **Program class**

```

if (args.Length > 0 && args[0].Length > 0)
{
    for (int i = 0; i < args.Length; i++)
    {
        filePath = args[i];

        if (!File.Exists(filePath))
        {
            Console.WriteLine($"File '{filePath}' does not exist");
            return;
        }

        var code = File.ReadAllText(filePath);

        var settings = new HTMLEmitterSettings();
        settings.DisableIframe();

        var colourer = new CsharpColourer();
        //colourer.Hints.ReallyPopularClasses.Add("UnityEvent");
        // colourer.Hints.ReallyPopularMethods.Add();
       // colourer.Hints.TeacherCodeToChange.Add("OnTriggerEnter");

        GettingDataFromINI data = new GettingDataFromINI();

        colourer.Hints.TeacherCodeToChange.AddRange(data.TeacherCodeToColor);
        colourer.Hints.ReallyPopularClasses.AddRange(data.PopularClassesToColor);
        colourer.Hints.ReallyPopularMethods.AddRange(data.PopularMethodsToColor);
        //.makeItYourOwn {
        //color: black;
        //padding: 3px;
        //background: linear - gradient(180deg, rgb(241, 242, 11) 0.00 %, rgb(248, 161, 27) 100.00 %);
        //    border - radius: 7px;
        //}

        string? html = null;

        if (args.Length == 1)
        {


            List<int> linesToHighlight = new List<int>();
            //for (int i = 1; i < args.Length; i++)
            //{
            //    linesToHighlight.Add(int.Parse(args[i]));
            //}

            bool highlightLineNumbers = true;
            while (highlightLineNumbers)
            {
                Console.Write("Enter a Line to Highlight (zero to move on): ");
                int lineNumber = int.Parse(Console.ReadLine()); // User inputs value into field.
                linesToHighlight.Add(lineNumber);

                if (lineNumber == 0)
                {
                    highlightLineNumbers = false;
                }
            }
            html = colourer.ProcessSourceCode(code, new HTMLEmitter(settings), linesToHighlight);
        }
        else
        {
            html = colourer.ProcessSourceCode(code, new HTMLEmitter(settings));
        }

        File.WriteAllText(new FileInfo(filePath).Directory?.FullName + @"\" + new FileInfo(filePath).Name + ".html", html);
}
}

```

**Comment by Swiftly1** [comment]
@kwalkerxxi 

I've prepared some sample implementation of highlighting https://github.com/Swiftly1/CsharpToColouredHTML/pull/19#issuecomment-1405781340

I think it'll be able to handle your usecase, lemme know what do you think.

**Comment by Swiftly1** [comment]
Implemented in https://github.com/Swiftly1/CsharpToColouredHTML/pull/19

Thanks for the feedback, I think both of those capabilities are really cool :) 

New version - 1.0.38 has been released.
